export const dummyData = [
  {
    home: "West Hoathly",
    away: "Oxted FC",
    date: "20 Aug 2022 14:00",
    venue: "Somewhere",
    result: {
      home: 0,
      away: 3,
    },
    highlights: [
      {
        team: "Oxted FC",
        name: "Buster Hoy",
        event: "goal",
        time: "8",
      },
      {
        team: "Oxted FC",
        name: "Jake Dadgson",
        event: "goal",
        time: "24",
      },
      {
        team: "Oxted FC",
        name: "Buster Hoy",
        event: "goal",
        time: "30",
      },
    ],
  },
  {
    home: "Oxted FC",
    away: "Crawley Devils",
    date: "11 Feb 2023 14:00",
    venue: "Master Park",
    result: {
      home: 5,
      away: 1,
    },
    highlights: [
      {
        team: "Oxted FC",
        name: "Mason Walker",
        event: "goal",
        time: "8",
      },
      {
        team: "Oxted FC",
        name: "Jake Dadgson",
        event: "goal",
        time: "24",
      },
      {
        team: "Oxted FC",
        name: "Buster Hoy",
        event: "goal",
        time: "30",
      },
      {
        team: "Oxted FC",
        name: "Aaron Crittall",
        event: "yellow card",
        time: "31",
      },
      {
        team: "Crawley Devils",
        name: "Harri Nourse",
        event: "goal",
        time: "54",
      },
      {
        team: "Oxted FC",
        name: "Jake Dadgson",
        event: "goal",
        time: "58",
      },
      {
        team: "Oxted FC",
        name: "Roman Kostka",
        event: "goal",
        time: "84",
      },
    ],
  },
  {
    home: "Sovereign Saints",
    away: "Oxted FC",
    date: "25 Feb 2023 13:30",
    venue: "Somewhere",
    result: {
      home: 5,
      away: 0,
    },
    highlights: [
      {
        team: "Oxted FC",
        name: "Buster Hoy",
        event: "goal",
        time: "8",
      },
      {
        team: "Oxted FC",
        name: "Jake Dadgson",
        event: "goal",
        time: "24",
      },
      {
        team: "Oxted FC",
        name: "Buster Hoy",
        event: "goal",
        time: "30",
      },
      {
        team: "Oxted FC",
        name: "Spencer Clements",
        event: "goal",
        time: "58",
      },
      {
        team: "Oxted FC",
        name: "Samuel Armitage",
        event: "goal",
        time: "84",
      },
    ],
  },
  {
    home: "Crawley Devils",
    away: "Oxted FC",
    date: "03 Sep 2022 14:00",
    venue: "Somewhere",
    result: null,
    highlights: null,
  },
  {
    home: "Oxted FC",
    away: "Hurstpierpoint",
    date: "13 Apr 2023 00:30",
    venue: "Master Park",
    result: null,
    highlights: null,
  },
  {
    home: "Oxted FC",
    away: "Sovereign Saints",
    date: "13 Apr 2023 00:30",
    venue: "Master Park",
    result: null,
    highlights: null,
  },
  {
    home: "Peacehaven & Telscombe II",
    away: "Oxted FC",
    date: "27 Aug 2022 14:00",
    venue: "Somewhere",
    result: null,
    highlights: null,
  },
  {
    home: "Oxted FC",
    away: "West Hoathly",
    date: "13 Apr 2023 00:30",
    venue: "Master Park",
    result: null,
    highlights: null,
  },
  {
    home: "Oxted FC",
    away: "Peacehaven & Telscombe II",
    date: "13 Apr 2023 00:30",
    venue: "Master Park",
    result: null,
    highlights: null,
  },
];

export const table = [
  {
    name: "Oxted FC",
    wins: 16,
    loses: 0,
    draws: 2,
    for: 59,
    against: 9,
  },
  {
    name: "Crawley Devils",
    wins: 11,
    loses: 5,
    draws: 2,
    for: 43,
    against: 29,
  },
  {
    name: "Ridgewood",
    wins: 10,
    loses: 6,
    draws: 2,
    for: 37,
    against: 22,
  },
  {
    name: "Ditchling",
    wins: 10,
    loses: 6,
    draws: 1,
    for: 44,
    against: 26,
  },
  {
    name: "Hurstpierpoint",
    wins: 7,
    loses: 6,
    draws: 5,
    for: 44,
    against: 46,
  },
  {
    name: "West Hoathly",
    wins: 7,
    loses: 4,
    draws: 7,
    for: 30,
    against: 40,
  },
  {
    name: "Sovereign Saints",
    wins: 7,
    loses: 8,
    draws: 2,
    for: 42,
    against: 36,
  },
  {
    name: "AFC Uckfield Town II",
    wins: 4,
    loses: 11,
    draws: 2,
    for: 30,
    against: 46,
  },
  {
    name: "Peacehaven & Telscombe II",
    wins: 3,
    loses: 12,
    draws: 1,
    for: 28,
    against: 61,
  },
  {
    name: "Roffey Dev",
    wins: 1,
    loses: 15,
    draws: 1,
    for: 21,
    against: 63,
  },
];

export const players = [
  {
    name: "John Wick",
    number: 1,
    position: "goalkeeper",
  },
  {
    name: "Ben Roy",
    number: 8,
    position: "centre back",
  },
  {
    name: "Emmanuel Blevins",
    number: 4,
    position: "centre midfielder",
  },
  {
    name: "Ben Connolly",
    number: 3,
    position: "striker",
  },
  {
    name: "Jake Dodgson",
    number: 7,
    position: "left midfielder",
  },
  {
    name: "Spencer Clements",
    number: 10,
    position: "left back",
  },
  {
    name: "James Heyburn",
    number: 46,
    position: "right back",
  },
  {
    name: "Stephen Hodge",
    number: 32,
    position: "striker",
  },
  {
    name: "Joseph Johnson",
    number: 5,
    position: "right midfielder",
  },
  {
    name: "Luke McClean",
    number: 21,
    position: "centre back",
  },
  {
    name: "Rhys Flitton",
    number: 30,
    position: "left back",
  },
  {
    name: "Samuel Armitage",
    number: 11,
    position: "central attacking midfielder",
  },
];
