export const Table = () => {
  return (
    <div className="container mx-auto">
      <table className="league-table">
        <thead>
          <tr>
            <th>Pos.</th>
            <th>Name</th>
            <th>Played</th>
            <th>Wins</th>
            <th>Draws</th>
            <th>Loses</th>
            <th>Points</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <p className="ordinal">1st</p>
            </td>
            <td>
              <p>Oxted FC</p>
            </td>
            <td>
              <p>18</p>
            </td>
            <td>
              <p>16</p>
            </td>
            <td>
              <p>2</p>
            </td>
            <td>
              <p>0</p>
            </td>
            <td>
              <p>50</p>
            </td>
          </tr>
          <tr>
            <td>
              <p className="ordinal">2nd</p>
            </td>
            <td>
              <p>Crawley Devils</p>
            </td>
            <td>
              <p>18</p>
            </td>
            <td>
              <p>11</p>
            </td>
            <td>
              <p>2</p>
            </td>
            <td>
              <p>5</p>
            </td>
            <td>
              <p>35</p>
            </td>
          </tr>
          <tr>
            <td>
              <p className="ordinal">3rd</p>
            </td>
            <td>
              <p>Ditchling</p>
            </td>
            <td>
              <p>17</p>
            </td>
            <td>
              <p>10</p>
            </td>
            <td>
              <p>1</p>
            </td>
            <td>
              <p>6</p>
            </td>
            <td>
              <p>31</p>
            </td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        </tbody>
      </table>
    </div>
  );
};
