const fixtures = [
  {
    id: 1,
    homeTeam: "Holland Sports",
    awayTeam: "Reigate Priory",
    time: "",
    date: "",
    venue: "",
    homeScore: 2,
    awayScore: 3,
    status: "completed",
    weekId: 1,
  },
  {
    id: 2,
    homeTeam: "Oxted FC",
    awayTeam: "Balcombe",
    time: "",
    date: "",
    venue: "",
    homeScore: 3,
    awayScore: 1,
    status: "completed",
    weekId: 1,
  },
  {
    id: 3,
    homeTeam: "Sedlescombe Rangers",
    awayTeam: "Crawley Devils",
    time: "",
    date: "",
    venue: "",
    homeScore: 0,
    awayScore: 3,
    status: "completed",
    weekId: 1,
  },
  {
    id: 4,
    homeTeam: "Westfield",
    awayTeam: "Cuckfield Rangers",
    time: "",
    date: "",
    venue: "",
    homeScore: 2,
    awayScore: 1,
    status: "completed",
    weekId: 1,
  },
  {
    id: 5,
    homeTeam: "Eastbourne United Association",
    awayTeam: "Battle Town",
    time: "",
    date: "",
    venue: "",
    homeScore: 0,
    awayScore: 0,
    status: "completed",
    weekId: 1,
  },
  {
    id: 6,
    homeTeam: "Battle Town",
    awayTeam: "Oxted FC",
    time: "",
    date: "",
    venue: "",
    homeScore: 0,
    awayScore: 0,
    status: "not started",
    weekId: 2,
  },
  {
    id: 7,
    homeTeam: "Cuckfield Rangers",
    awayTeam: "Reigate Priory",
    time: "",
    date: "",
    venue: "",
    homeScore: 0,
    awayScore: 0,
    status: "not started",
    weekId: 2,
  },
  {
    id: 8,
    homeTeam: "Holland Sports",
    awayTeam: "Crawley Devils",
    time: "",
    date: "",
    venue: "",
    homeScore: 0,
    awayScore: 0,
    status: "not started",
    weekId: 2,
  },
  {
    id: 9,
    homeTeam: "Ringmer AFC",
    awayTeam: "Westfield",
    time: "",
    date: "",
    venue: "",
    homeScore: 0,
    awayScore: 0,
    status: "not started",
    weekId: 2,
  },

  {
    id: 10,
    homeTeam: "Rotherfield",
    awayTeam: "Copthorne II",
    time: "",
    date: "",
    venue: "",
    homeScore: 0,
    awayScore: 0,
    status: "not started",
    weekId: 2,
  },
  {
    id: 11,
    homeTeam: "Sedlescombe Rangers",
    awayTeam: "Eastbourne United Association",
    time: "",
    date: "",
    venue: "",
    homeScore: 0,
    awayScore: 0,
    status: "not started",
    weekId: 2,
  },
  {
    id: 12,
    homeTeam: "",
    awayTeam: "",
    time: "",
    date: "",
    venue: "",
    homeScore: 0,
    awayScore: 0,
    status: "not started",
    weekId: 3,
  },
  {
    id: 13,
    homeTeam: "",
    awayTeam: "",
    time: "",
    date: "",
    venue: "",
    homeScore: 0,
    awayScore: 0,
    status: "not started",
    weekId: 3,
  },
  {
    id: 14,
    homeTeam: "",
    awayTeam: "",
    time: "",
    date: "",
    venue: "",
    homeScore: 0,
    awayScore: 0,
    status: "not started",
    weekId: 3,
  },
  {
    id: 15,
    homeTeam: "",
    awayTeam: "",
    time: "",
    date: "",
    venue: "",
    homeScore: 0,
    awayScore: 0,
    status: "not started",
    weekId: 3,
  },
  {
    id: 16,
    homeTeam: "",
    awayTeam: "",
    time: "",
    date: "",
    venue: "",
    homeScore: 0,
    awayScore: 0,
    status: "not started",
    weekId: 3,
  },
  {
    id: 17,
    homeTeam: "",
    awayTeam: "",
    time: "",
    date: "",
    venue: "",
    homeScore: 0,
    awayScore: 0,
    status: "not started",
    weekId: 3,
  },
];

const weeks = [
  {
    id: 1,
    week: 1,
    wc: "12/08/2023",
    status: "completed",
  },
  {
    id: 2,
    week: 2,
    wc: "19/08/2023",
    status: "not started",
  },
  {
    id: 3,
    week: 3,
    wc: "26/08/2023",
    status: "not started",
  },
  {
    id: 4,
    week: 4,
    wc: "02/09/2023",
    status: "not started",
  },
  {
    id: 5,
    week: 5,
    wc: "09/09/2023",
    status: "not started",
  },
];

const players = [
  {
    name: "John Wick",
    number: 1,
    position: "goalkeeper",
    appearances: 6,
    goals: 0,
    penalties: 0,
    assists: 0,
    yellowCards: 0,
    redCards: 0,
    started: 0,
    mom: 0,
    cleanSheets: 0,
  },
  {
    name: "Ben Roy",
    number: 8,
    position: "centre back",
    appearances: 7,
    goals: 0,
    penalties: 0,
    assists: 0,
    yellowCards: 0,
    redCards: 0,
    started: 0,
    mom: 0,
    cleanSheets: 0,
  },
  {
    name: "Emmanuel Blevins",
    number: 4,
    position: "centre midfielder",
    appearances: 7,
    goals: 0,
    penalties: 0,
    assists: 0,
    yellowCards: 0,
    redCards: 0,
    started: 0,
    mom: 0,
    cleanSheets: 0,
  },
  {
    name: "Ben Connolly",
    number: 3,
    position: "striker",
    appearances: 7,
    goals: 0,
    penalties: 0,
    assists: 0,
    yellowCards: 0,
    redCards: 0,
    started: 0,
    mom: 0,
    cleanSheets: 0,
  },
  {
    name: "Jake Dodgson",
    number: 7,
    position: "left midfielder",
    appearances: 7,
    goals: 0,
    penalties: 0,
    assists: 0,
    yellowCards: 0,
    redCards: 0,
    started: 0,
    mom: 0,
    cleanSheets: 0,
  },
  {
    name: "Spencer Clements",
    number: 10,
    position: "left back",
    appearances: 7,
    goals: 0,
    penalties: 0,
    assists: 0,
    yellowCards: 0,
    redCards: 0,
    started: 0,
    mom: 0,
    cleanSheets: 0,
  },
  {
    name: "James Heyburn",
    number: 46,
    position: "right back",
    appearances: 7,
    goals: 0,
    penalties: 0,
    assists: 0,
    yellowCards: 0,
    redCards: 0,
    started: 0,
    mom: 0,
    cleanSheets: 0,
  },
  {
    name: "Stephen Hodge",
    number: 32,
    position: "striker",
    appearances: 7,
    goals: 0,
    penalties: 0,
    assists: 0,
    yellowCards: 0,
    redCards: 0,
    started: 0,
    mom: 0,
    cleanSheets: 0,
  },
  {
    name: "Joseph Johnson",
    number: 5,
    position: "right midfielder",
    appearances: 7,
    goals: 0,
    penalties: 0,
    assists: 0,
    yellowCards: 0,
    redCards: 0,
    started: 0,
    mom: 0,
    cleanSheets: 0,
  },
  {
    name: "Luke McClean",
    number: 21,
    position: "centre back",
    appearances: 7,
    goals: 0,
    penalties: 0,
    assists: 0,
    yellowCards: 0,
    redCards: 0,
    started: 0,
    mom: 0,
    cleanSheets: 0,
  },
  {
    name: "Rhys Flitton",
    number: 30,
    position: "left back",
    appearances: 6,
    goals: 0,
    penalties: 0,
    assists: 0,
    yellowCards: 0,
    redCards: 0,
    started: 0,
    mom: 0,
    cleanSheets: 0,
  },
  {
    name: "Samuel Armitage",
    number: 11,
    position: "central attacking midfielder",
    appearances: 7,
    goals: 0,
    penalties: 0,
    assists: 0,
    yellowCards: 0,
    redCards: 0,
    started: 0,
    mom: 0,
    cleanSheets: 0,
  },
];

module.exports = { fixtures, weeks, players };
