export const teams = [
  "Oxted & District",
  "Eastbourne United Association",
  "Reigate Priory",
  "Ringmer AFC",
  "Crawley Devils",
  "Westfield",
  "Cuckfield Rangers",
  "Lindfield",
  "Rotherfield",
  "Holland Sports",
  "Battle Town",
  "Balcombe",
  "Copthorne II",
  "Sedlescombe Rangers",
];

export const mainTeam = "Oxted & District";

export const status = ["Not started", "In progress", "Completed"];

export const table = [
  {
    name: "Oxted & District",
    played: 0,
    wins: 0,
    draws: 0,
    loses: 0,
    for: 0,
    against: 0,
    points: 0,
  },
  {
    name: "Eastbourne United Association",
    played: 0,
    wins: 0,
    draws: 0,
    loses: 0,
    for: 0,
    against: 0,
    points: 0,
  },
  {
    name: "Reigate Priory",
    played: 0,
    wins: 0,
    draws: 0,
    loses: 0,
    for: 0,
    against: 0,
    points: 0,
  },
  {
    name: "Ringmer AFC",
    played: 0,
    wins: 0,
    draws: 0,
    loses: 0,
    for: 0,
    against: 0,
    points: 0,
  },
  {
    name: "Crawley Devils",
    played: 0,
    wins: 0,
    draws: 0,
    loses: 0,
    for: 0,
    against: 0,
    points: 0,
  },
  {
    name: "Westfield",
    played: 0,
    wins: 0,
    draws: 0,
    loses: 0,
    for: 0,
    against: 0,
    points: 0,
  },
  {
    name: "Cuckfield Rangers",
    played: 0,
    wins: 0,
    draws: 0,
    loses: 0,
    for: 0,
    against: 0,
    points: 0,
  },
  {
    name: "Rotherfield",
    played: 0,
    wins: 0,
    draws: 0,
    loses: 0,
    for: 0,
    against: 0,
    points: 0,
  },
  {
    name: "Holland Sports",
    played: 0,
    wins: 0,
    draws: 0,
    loses: 0,
    for: 0,
    against: 0,
    points: 0,
  },
  {
    name: "Battle Town",
    played: 0,
    wins: 0,
    draws: 0,
    loses: 0,
    for: 0,
    against: 0,
    points: 0,
  },
  {
    name: "Balcombe",
    played: 0,
    wins: 0,
    draws: 0,
    loses: 0,
    for: 0,
    against: 0,
    points: 0,
  },
  {
    name: "Copthorne II",
    played: 0,
    wins: 0,
    draws: 0,
    loses: 0,
    for: 0,
    against: 0,
    points: 0,
  },
  {
    name: "Sedlescombe Rangers",
    played: 0,
    wins: 0,
    draws: 0,
    loses: 0,
    for: 0,
    against: 0,
    points: 0,
  },
];
